// <auto-generated />
using System;
using Entity_Framework;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EntityFramework.Migrations
{
    [DbContext(typeof(MyAppDataContext))]
    partial class MyAppDataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entity_Framework.Models.Club", b =>
                {
                    b.Property<string>("Club_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("club_name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Club_id");

                    b.ToTable("Clubs");
                });

            modelBuilder.Entity("Entity_Framework.Models.Course", b =>
                {
                    b.Property<int>("Course_id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Course_id"));

                    b.Property<string>("Couse_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Course_id");

                    b.ToTable("Courses");
                });

            modelBuilder.Entity("Entity_Framework.Models.Student", b =>
                {
                    b.Property<int>("student_Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("student_Id"));

                    b.Property<string>("Club_id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int?>("Course_id")
                        .HasColumnType("int");

                    b.Property<string>("student_Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("student_dob")
                        .HasColumnType("datetime2");

                    b.HasKey("student_Id");

                    b.HasIndex("Club_id");

                    b.HasIndex("Course_id");

                    b.ToTable("Students");
                });

            modelBuilder.Entity("Entity_Framework.Models.Student", b =>
                {
                    b.HasOne("Entity_Framework.Models.Club", null)
                        .WithMany("Students")
                        .HasForeignKey("Club_id");

                    b.HasOne("Entity_Framework.Models.Course", null)
                        .WithMany("Students")
                        .HasForeignKey("Course_id");
                });

            modelBuilder.Entity("Entity_Framework.Models.Club", b =>
                {
                    b.Navigation("Students");
                });

            modelBuilder.Entity("Entity_Framework.Models.Course", b =>
                {
                    b.Navigation("Students");
                });
#pragma warning restore 612, 618
        }
    }
}
